# Generated by Django 3.0.8 on 2020-08-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200803_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
